content:
  - name: htmlpages
    label: "HTML Pages"
    type: collection
    path: "restaurant-caspari.de/de"
    format: code                       # code editor
    subfolders: false
    fields:
      - name: content
        label: "HTML Source"
        type: code
        parser: html                   # tells Pages CMS this is HTML
        options:
          language: html