content:
  - name: htmlpages
    label: "HTML Pages"
    type: collection
    path: "restaurant-caspari.de/de"      # point at the folder, not a glob [2]
    format: raw                            # use the “raw” editor for the entire file [2]
    subfolders: false                      # don’t recurse into subfolders (optional)
