content:
  - name: subsites
    label: HTML Subsites
    type: collection
    path: "de"  # Targets your /de directory
    view:
      fields: [title, section, content]
    fields:
      - name: title
        label: Page Title
        type: string
        required: true
        
      - name: section
        label: Content Section
        type: string
        list: true
        options: [about, menu, contact]  # Customize sections
        
      - name: content
        label: HTML Content
        type: rich-text  # or 'code' for raw HTML editing
        description: Edit main content area