media: "files"
content:
  - name: "htmlpages"
    label: "HTML Pages"
    type: "collection"
    path: "restaurant-caspari.de/de/*.html"
    parser: "html"  # Specify the parser explicitly
    fields:
      - name: "body"
        label: "Content"
        type: "markdown"  # Try changing from "code" to "markdown"
        parser: "html"    # Explicitly set parser for this field

