content:
  - name: pages
    label: HTML Pages
    type: collection
    path: "de/*.html"  # Targets your German subsites
    fields:
      - name: body
        label: Page Content
        type: rich-text
        required: true