media: "files"
content:
  - name: "pages"
    label: "HTML Pages"
    path: "restaurant-caspari.de/de"
    pattern: "**/*.html"  # Use pattern instead of path with glob
    fields:
      - name: "content"
        label: "Page Content"
        type: "html"      # Use simple "html" type instead of "code"

