media: "files"  # Adjust to your media folder location

content:
  - name: "htmlpages"
    label: "HTML Pages"
    type: "collection"
    path: "restaurant-caspari.de/de/*.html"
    format: "code"  # This is crucial for HTML files
    view:
      primary: "body"
      fields: ["body"]



