media: "files"  # Adjust to your media folder location

content:
  - name: "pages"
    label: "HTML Pages"
    type: "collection"
    path: "restaurant-caspari.de/de"  # Path to your HTML files
    fields:
      - name: "title"
        label: "Page Title"
        type: "string"
      - name: "body"
        label: "Page Content"
        type: "code"
        format: "html"  # Specifying HTML format
