media: "files"  # Adjust to your media folder location

content:
  - name: "mainpages"
    label: "Main Pages"
    type: "collection"
    path: "restaurant-caspari.de/de/*.html"
    fields: ["title", "filename"]
      # Fields configuration as above

  - name: "subpages"
    label: "Sub Pages"
    type: "collection"
    path: "restaurant-caspari.de/de/*/*.html"  # For HTML files in subdirectories
    fields:
      # Fields configuration

