media: "files"  # Adjust to your media folder location

content:
  - name: "mainsite"
    label: "Main Site Pages"
    type: "collection"
    path: "restaurant-caspari.de/de/*.html"  # Target HTML files
    view:
      fields: ["title", "filename"]  # Show these fields in the admin list view
    fields:
      - name: "title"
        label: "Page Title"
        type: "string"
      - name: "body"
        label: "Page Content"
        type: "code"
        format: "html"
