branch: main                    # the branch you want Pages CMS to watch
base_url: https://restaurant-caspari.de
paths:
  '/de':                        # URL prefix
    - 'de/**/*.html'            # all HTML files under the de/ directory